---
version: '3'

services:
  nginx:
    image: nginx
    restart: always
    depends_on:
      - guacamole
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx.key:/etc/ssl/private/nginx.key:ro
      - ./nginx.crt:/etc/ssl/certs/nginx.crt:ro
  guacd:
    image: guacamole/guacd
    restart: always
    # -------------------------------
    # Comment out for Productive use
    # -------------------------------
    ports:
      - 4822:4822
    # -------------------------------
  guacamole:
    image: guacamole/guacamole
    restart: always
    depends_on:
      - mysql
    # -------------------------------
    # Comment out for Productive use
    # -------------------------------
    ports:
      - 8080:8080
    # -------------------------------
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: guacamole
      MYSQL_USER: guacamole
      MYSQL_PASSWORD: guacamole
  mysql:
    image: mysql
    restart: always
    # -------------------------------
    # Comment out for Productive use
    # -------------------------------
    ports:
      - "3306:3306"
    # -------------------------------
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guacamole
      MYSQL_USER: guacamole
      MYSQL_PASSWORD: guacamole
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;'
  # -------------------------------
  # Comment out for Productive use
  # -------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    restart: always
    ports:
      - 8000:80
   # -------------------------------
